server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: myshorturl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myblog
    username: root
    password: 1111
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 100        # 最大连接数量
        max-idle: 10           # 最大空闲数量
        min-idle: 10           # 最小空闲数量
        max-wait: 3000ms # 获取连接时的最大等待毫秒数
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
url:
  start: http://tulip.im/