server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: myshorturl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.32.186.138:3306/check?rewriteBatchedStatements=true
    username: check
    password: jaRdZhfXR4KfLb3F
    hikari:
     minimum-idle: 5  #最小空闲连接数量
     idle-timeout: 0 #空闲连接存活最大时间，默认600000（10分钟）
     maximum-pool-size: 10 #连接池最大连接数，默认是10
     auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
     pool-name: MyHikariCP # 连接池母子
     max-lifetime: 0 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
     connection-timeout: 0 # 数据库连接超时时间,默认30秒，即30000



  #  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    database: 0
#    jedis:
#      pool:
#        max-active: 100        # 最大连接数量
#        max-idle: 10           # 最大空闲数量
#        min-idle: 10           # 最小空闲数量
#        max-wait: 3000ms # 获取连接时的最大等待毫秒数
  jpa:
    properties:
      hibernate:
       # generate_statistics: true
        jdbc:
          batch_size: 10000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        hbm2ddl:
          auto: update
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: false
url:
  start: http://tulip.im/